KanbanSite/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import about_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls')),
    path('cards/',include('cards.urls')),
    path('board/',include('board.urls')),
    path('', include('home.urls')),
    path('about/',about_view,name='about_view'),
]

accounts/urls.py
from django.urls import path
from .views import user_register_view

app_name = 'accounts'

urlpatterns = [
    path('register/',user_register_view,name='register_view')
]

board/urls.py
from django.urls import path
from .views import board_view,board_list_view

app_name = 'board'

urlpatterns = [
    path('',board_view, name ='board_view'),
    path('board_list/',board_list_view,name='board_list_view')
]

cards/urls.py
from django.urls import path
from .views import add_card_view, edit_card_details

app_name = 'cards'

urlpatterns = [
    path('add/',add_card_view, name='add_card_view'),
    path('<int:id>/edit/',edit_card_details, name ='edit_view'),
]

home/urls.py
from django.urls import path
from .views import home_view,about_view

app_name = 'home'

urlpatterns = [
    path('',home_view, name='home_view'),
    path('about/',about_view,name='about_view')
]

accounts/models.py
from django.db import models

board/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Board(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=100,default="Board_1",editable=False)

cards/models.py
from django.db import models
from django.urls import reverse
from board.models import Board
# Create your models here.

class Card(models.Model):
    TODO = 'todo'
    IN_PROGRESS = 'inpr'
    DONE = 'done'
    KANBAN_CHOICES = [
        (TODO, "To-Do"),
        (IN_PROGRESS, "In-Progress"),
        (DONE, "Done")
    ]
    board=models.ForeignKey(Board,on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    description = models.TextField(blank=False,null=False)
    stage = models.CharField(max_length=4,
        choices=KANBAN_CHOICES,
        default=TODO,)


    date_created = models.DateField(auto_now=False,auto_now_add=True)

    def get_absolute_url(self):
        return reverse("cards:edit_view",kwargs={"id":self.id})

home/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserForm(UserCreationForm):
    email = forms.EmailField(max_length=255,help_text='Required.')
    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password1',
            'password2'
        ]
        labels = {
            'username' : "UserName"
        }
        help_text = {
            'password1': "",
        }

    # def __init__(self, user, *args, **kwargs):
    #     super(UserForm,self).__init__(*args,**kwargs)
    #
    #     self.fields['password1'].help_text = None

cards/forms.py
from django import forms

from .models import Card


class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = [
            'title',
            'description',
            'stage'
        ]

    def save(self,board):
        card = super(CardForm,self).save(commit=False)
        card.board = board
        card.save()
        return card

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import login, authenticate
from django.core.validators import validate_email
from .forms import UserForm
from board.models import Board
# Create your views here.

def user_register_view(request):
    context = {

    }
    if request.method == 'POST':
        form = UserForm(request.POST or none)
        print(form)
        if form.is_valid():
            print(form.cleaned_data)
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username,password=raw_password)
            # user = User.objects.create_user(**form.cleaned_data)
            login(request,user)
            Board.objects.create(user=user,title=username+" Board")
            return HttpResponseRedirect('/board/')
        else:
            print("Invalid Information")

        return render(request,'registration/registration.html',context)

    return render(request,'registration/registration.html',context)

board/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseNotFound
from cards.models import Card
from board.models import Board
import itertools
# from django.apps import apps
# Create your views here.


def board_view(request):
    if request.user.is_authenticated:
        board = Board.objects.get(user=request.user)
        todoItems = Card.objects.filter(board=board,stage='todo')
        inprogItems = Card.objects.filter(board=board,stage='inpr')
        doneItems = Card.objects.filter(board=board,stage='done')

        queryItems = list(itertools.zip_longest(todoItems,inprogItems,doneItems))

        context = {
            "zipCards" : queryItems
        }
        
        return render(request, "board/board_detail.html",context)
    else:
        return HttpResponseNotFound('<h1>Page not found</h1>')

def board_list_view(request):
    context = {
    }
    return render(request,"board/board_list.html",context)

cards/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponseNotFound
from .models import Card
from .forms import CardForm
from board.models import Board
# Create your views here.


def add_card_view(request):
    if not request.user.is_authenticated:
        return HttpResponseNotFound('<h1>Page Not Found</h1>')
    form = CardForm(request.POST or None)
    if form.is_valid():
        print(request.user)
        board = Board.objects.get(user=request.user)
        print(board)
        form.save(board)
        form = CardForm()
        return HttpResponseRedirect('/board/')
    context = {
        "form": form
    }
    return render(request, "cards/add_card.html",context)

def edit_card_details(request,id):
    obj = Card.objects.get(id=id)
    form = CardForm(request.POST or None,instance=obj)
    context = {
        "form": form
    }
    if request.POST.get("Save"):
        print('Save')
        if form.is_valid():
            board = Board.objects.get(user=request.user)
            print(board)
            form.save(board)
            form = CardForm()
            return HttpResponseRedirect('/board/')
        else:
            print('invalide')
    elif request.POST.get("Delete"):
        print("Delete1")
        obj = get_object_or_404(Card,id=id)
        if request.method == "POST":
            obj.delete()
        return HttpResponseRedirect('/board/')
    return render(request, "cards/add_card.html",context)

home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.validators import validate_email
from accounts.forms import UserForm
# Create your views here.


def home_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/board/')

    if request.method == "POST":
        print("YES")
        email = request.POST.get('register')
        print(email)
        if email is None or email is "":
            return HttpResponseRedirect('/')
        try:
            validate_email(email)
            initial_data = {
                'email': email,
            }
            form = UserForm(initial=initial_data)
            context = {
                'form': form,
            }
            return render(request,'registration/registration.html',context)
        except:
            print("Invalid Email")
            return HttpResponseRedirect('/')

    return render(request,"home.html")


def about_view(request):
    text = "Johann Lau is a computer science masters student at Georgia Tech that is willing to learn and grow as a software developer. His experience with software design and testing, solution architect, and cybersecurity provides an holistic and technical approach to problem solving."
    context = {
        "about_me" : text,
    }
    return render(request,"about/about_me.html",context)

templates/about/about_me.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">
{% endblock %}


{% block content %}
{% include 'navbar.html' %}
<div class="professional_container">
  <h2>About This Project</h2>
  <hr>
  <p>This is a side project dedicated to learning the in and outs of the Django Framework. </p>
  <p id ="aboutme_link"> For more information <a href="https://j-l5662.github.io">about me</a></p>
  <br>

</div>




{% endblock %}

templates/base.html
{% load static %}
<!Doctype html>
<html>
<head>
  <title>Kanban Site</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  {% block style %}
  <link rel="stylesheet" type="text/css" href="{% static 'board/style.css' %}">
  {% endblock %}
</head>
<body>
  {% block content %}
  {% include 'navbar.html' %}
  <div class="container">
  <h1>KanBan Site</h1>
    <p>This is the first card!</p>
  </div>
  {% endblock %}
  {% block content2 %}
  {% endblock %}
</body>
</html>

templates/board/board_detail.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'board/style.css' %}">
<link  href="http://fonts.googleapis.com/css?
family=Reenie+Beanie:regular"
rel="stylesheet"
type="text/css">
{% endblock %}
{% block content %}
{% include 'board/board_navbar.html' %}
<h1>{{request.user|title}}'s Site</h1>
{% endblock %}
{% block content2 %}
<table id="board_id" border="3" width="100%" style="margin: 5px; margin-left: 5px;">
  <tr>
   <th class="column">TODO</th>
   <th class="column">In-Progress</th>
   <th class="column">Completed</th>
  </tr>
  <!-- for loop to get the data into the  -->
  {% for card in zipCards %}
  <tr>
      {% if not card.0 %}
        <td id = "empty" align="center"/>
      {% else %}
        <td id = "card_item" align="center">
          <a href='{{ card.0.get_absolute_url }}'>
            <h3>{{card.0.title}} </h3>
            <p> {{card.0.description}} </p>
           </a>
        </td>
      {% endif %}
      {% if card.1 == None %}
        <td id = "empty" align="center"/>
      {% else %}
      <td id = "card_item" align="center">
        <a href='{{ card.1.get_absolute_url }}'>
          <h3>{{card.1.title}} </h3>
          <p> {{card.1.description}} </p>
        </a>
      </td>
      {% endif %}
      {% if card.2 == None %}
        <td id = "empty" align="center"/>
      {% else %}
      <td id = "card_item" align="center">
        <a href='{{ card.2.get_absolute_url }}'>
          <h3>{{card.2.title}} </h3>
          <p> {{card.2.description}} </p>
        </a>
      </td>
      {% endif %}
  </tr>
  {% endfor %}

  <tr>
    <td class = "add_card_link" align="center">
      <a href='/cards/add'>Add</a>
    </td>
    <td class = "add_card_link" align="center">
      <a href='/cards/add'>Add</a>
    </td><td class = "add_card_link" align="center">
      <a href='/cards/add'>Add</a>
    </td>
  </tr>
</table>

{% endblock %}

templates/board/board_list.html
<h1>Coming Soon.. </h1>

templates/board/board_navbar.html
<div>
  <a class="active" href="{% url 'board:board_view' %}">Home</a>
  <a href="{% url 'board:board_list_view' %}">Boards</a>
  <a href="#setting">Settings</a>
  <a href="{% url 'logout' %}">Sign Out</a>
</div>

templates/cards/add_card.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'cards/style.css' %}">
{% endblock %}
{% block content %}

<div id= "card_col">

  <div id="card_form">
    <div id="cancel_button">
    <a href="{% url 'board:board_view' %}">&times;</a>
    </div>
    <form id="form" method='POST'> {% csrf_token %}
      {% for field in form %}
      <p>
        {{ field.label_tag}} <br> {{ field }}
      </p>
      {% endfor %}
      <input type='submit' name='Save' value='Save'/>
      <input type='submit' name='Delete' value='Delete'/>
    </form>
  </div>
</div>
{% endblock %}

templates/cards/edit_card_details.html
{% extends 'base.html' %}

{% block content %}

<form method='POST'> {% csrf_token %}
  {{form.as_p}}
  <input type='submit' value='Save'/>
  <button type='submit' value='Cancel'>
    <a href="/home">Cancel</a>
  </button>
</form>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">
{% endblock %}


{% block content %}
{% include 'navbar.html' %}
<h1 align="center">Sjmple KanBan</h1>
<p align="center">A simple Kanban board to visualize your work.</p>

<div align="center" >
  <form action="{% url 'home:home_view' %}" method="POST"> {% csrf_token %}
    <input type='text' name='register' placeholder="Email"/>
    <input type='submit' value="Register"/>
  </form>

</div>
<div align="center" >
  <p> Already using Sjmple?
  <a href = "{% url 'login' %}" id="login"> Login </a>
  </p>
</div>
{% endblock %}

templates/navbar.html
{% load static %}
<style>
  #title_logo {
    color: blue;
    display: inline;
    white-space: nowrap;
  }
  #navbar {
    margin-left:5px;
    margin-top:5px;
  }
</style>
<div id="navbar">
  <a id="title_logo" href="/">Sjmple Kanban</a>
  <a href="{% url 'home:about_view' %}">About</a>
</div>